name: CI/CD para Poupe.AI Notification Service

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:
    IMAGE_NAME: franciscopaulino/poupei-notification-service
    INFRA_DIR: /home/deployer/poupei-infra

jobs:
    build_and_push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout do código
              uses: actions/checkout@v4

            - name: Login no Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            
            - name: Build e push da imagem Docker
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: ${{ env.IMAGE_NAME }}:latest

    deploy:
        needs: build_and_push
        runs-on: ubuntu-latest
        
        steps:
            - name: Deploy para o servidor
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.VPS_HOST }}
                username: ${{ secrets.VPS_USER }}
                key: ${{ secrets.VPS_SSH_KEY }}
                script: |
                    echo "--- Login no Docker Hub ---"
                    echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

                    echo "--- Navegando para o diretório de infra ---"
                    cd ${{ env.INFRA_DIR }}

                    echo "--- Atualizando a imagem do serviço --"
                    docker compose pull notification-service

                    echo "--- Recriando o contêiner notification-service ---"
                    docker compose up -d --no-deps notification-service

                    echo "--- Limpando imagens antigas ---"
                    docker image prune -af
